#!/bin/sh

set -eu

if ! git --version >/dev/null; then
  echo "git not installed"
  exit 1
fi

./contrib/gana.sh

# This is more portable than `which' but comes with
# the caveat of not(?) properly working on busybox's ash:
existence()
{
    command -v "$1" >/dev/null 2>&1
}


if existence uncrustify; then
    echo "Installing uncrustify hook and configuration"
    # Install uncrustify format symlink (if possible)
    ln -s contrib/uncrustify.cfg uncrustify.cfg 2> /dev/null || true
    # Install pre-commit hook (if possible)
    ln -s ../../contrib/uncrustify_precommit .git/hooks/pre-commit 2> /dev/null || true
else
    echo "Uncrustify not detected, hook not installed. Please install uncrustify if you plan on doing development"
fi

autoreconf -fi
